/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const GhostStatus = IDL.Variant({
  'rejected' : IDL.Null,
  'accepted' : IDL.Null,
  'unknown' : IDL.Null,
  'received' : IDL.Null,
});
export const Time = IDL.Int;
export const TradeStatus = IDL.Variant({
  'canceled' : IDL.Null,
  'submitted' : IDL.Null,
  'filled' : IDL.Null,
  'working' : IDL.Null,
  'rejected' : IDL.Null,
  'unknown' : IDL.Null,
});
export const TraceQueryFilters = IDL.Record({
  'ticker' : IDL.Opt(IDL.Text),
  'strategy' : IDL.Opt(IDL.Text),
  'ghost_status' : IDL.Opt(GhostStatus),
  'end_time' : IDL.Opt(Time),
  'start_time' : IDL.Opt(Time),
  'tradovate_status' : IDL.Opt(TradeStatus),
});
export const TraceId = IDL.Text;
export const Trace = IDL.Record({
  'pnl' : IDL.Opt(IDL.Float64),
  'updated_at' : Time,
  'action' : IDL.Text,
  'ticker' : IDL.Text,
  'take_profit' : IDL.Float64,
  'alert_received_at' : Time,
  'duration_seconds' : IDL.Opt(IDL.Nat64),
  'strategy' : IDL.Text,
  'ghost_status' : GhostStatus,
  'created_at' : Time,
  'entry' : IDL.Float64,
  'avg_entry' : IDL.Opt(IDL.Float64),
  'stop_loss' : IDL.Float64,
  'trace_id' : TraceId,
  'avg_exit' : IDL.Opt(IDL.Float64),
  'tradovate_status' : TradeStatus,
});
export const RiskMethod = IDL.Variant({
  'percentBalance' : IDL.Null,
  'fixedQuantity' : IDL.Null,
});
export const Settings = IDL.Record({
  'pipeline_test_mode' : IDL.Bool,
  'ghost_exit_warn_ratio' : IDL.Float64,
  'ghost_api_key' : IDL.Text,
  'tradovate_live_url' : IDL.Text,
  'ghost_markup_pct' : IDL.Float64,
  'ghost_exit_warn_time_sec' : IDL.Nat64,
  'risk_method' : RiskMethod,
  'max_trade_quantity' : IDL.Nat,
  'ghost_executed_from_devices' : IDL.Vec(IDL.Text),
  'ghost_webhook_url' : IDL.Text,
  'tradovate_api_key' : IDL.Text,
  'tradovate_demo_url' : IDL.Text,
  'ghost_trade_max_qty_scale' : IDL.Nat,
  'ghost_spread_threshold' : IDL.Float64,
});
export const EventSource = IDL.Variant({
  'tradovate' : IDL.Null,
  'ghost' : IDL.Null,
  'tradingview' : IDL.Null,
});
export const EventType = IDL.Variant({
  'tradingviewEvent' : IDL.Null,
  'ghostForwardAttempt' : IDL.Null,
  'validationError' : IDL.Null,
  'ghostForwardSuccess' : IDL.Null,
  'ghostForwardFailure' : IDL.Null,
  'alertReceived' : IDL.Null,
  'ghostCallback' : IDL.Null,
});
export const TraceEvent = IDL.Record({
  'id' : IDL.Nat,
  'source' : EventSource,
  'trace_id' : TraceId,
  'event_time' : Time,
  'event_type' : EventType,
});
export const Fill = IDL.Record({
  'fill_time' : Time,
  'trace_id' : TraceId,
  'price' : IDL.Float64,
});
export const WebhookStatus = IDL.Variant({
  'error' : IDL.Text,
  'processed' : IDL.Null,
  'received' : IDL.Null,
});
export const WebhookAlert = IDL.Record({
  'status' : WebhookStatus,
  'received_at' : Time,
  'action' : IDL.Opt(IDL.Text),
  'ticker' : IDL.Opt(IDL.Text),
  'strategy' : IDL.Opt(IDL.Text),
  'alert_name' : IDL.Opt(IDL.Text),
  'raw_payload' : IDL.Text,
  'alert_id' : IDL.Text,
});
export const TraceInput = IDL.Record({
  'action' : IDL.Text,
  'ticker' : IDL.Text,
  'take_profit' : IDL.Float64,
  'strategy' : IDL.Text,
  'params_snapshot_json' : IDL.Text,
  'entry' : IDL.Float64,
  'stop_loss' : IDL.Float64,
});
export const ReceiveWebhookResponse = IDL.Record({
  'ok' : IDL.Bool,
  'error' : IDL.Opt(IDL.Text),
  'trace_id' : IDL.Opt(TraceId),
});

export const idlService = IDL.Service({
  'filterTraces' : IDL.Func([TraceQueryFilters], [IDL.Vec(Trace)], ['query']),
  'getSettings' : IDL.Func([], [Settings], ['query']),
  'getTrace' : IDL.Func([TraceId], [IDL.Opt(Trace)], ['query']),
  'getTraceEvents' : IDL.Func([TraceId], [IDL.Vec(TraceEvent)], ['query']),
  'getTraceFills' : IDL.Func([TraceId], [IDL.Vec(Fill)], ['query']),
  'getWebhookAlert' : IDL.Func([IDL.Text], [IDL.Opt(WebhookAlert)], ['query']),
  'getWebhookAlerts' : IDL.Func([], [IDL.Vec(WebhookAlert)], ['query']),
  'listTraces' : IDL.Func([], [IDL.Vec(Trace)], ['query']),
  'receiveGhostCallback' : IDL.Func([IDL.Text], [], []),
  'receiveWebhook' : IDL.Func(
      [IDL.Opt(TraceInput), TraceId],
      [ReceiveWebhookResponse],
      [],
    ),
  'refreshTrace' : IDL.Func([TraceId], [], []),
  'saveSettings' : IDL.Func([Settings], [], []),
  'updateGhostStatus' : IDL.Func(
      [TraceId, GhostStatus, IDL.Text, IDL.Opt(IDL.Text)],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const GhostStatus = IDL.Variant({
    'rejected' : IDL.Null,
    'accepted' : IDL.Null,
    'unknown' : IDL.Null,
    'received' : IDL.Null,
  });
  const Time = IDL.Int;
  const TradeStatus = IDL.Variant({
    'canceled' : IDL.Null,
    'submitted' : IDL.Null,
    'filled' : IDL.Null,
    'working' : IDL.Null,
    'rejected' : IDL.Null,
    'unknown' : IDL.Null,
  });
  const TraceQueryFilters = IDL.Record({
    'ticker' : IDL.Opt(IDL.Text),
    'strategy' : IDL.Opt(IDL.Text),
    'ghost_status' : IDL.Opt(GhostStatus),
    'end_time' : IDL.Opt(Time),
    'start_time' : IDL.Opt(Time),
    'tradovate_status' : IDL.Opt(TradeStatus),
  });
  const TraceId = IDL.Text;
  const Trace = IDL.Record({
    'pnl' : IDL.Opt(IDL.Float64),
    'updated_at' : Time,
    'action' : IDL.Text,
    'ticker' : IDL.Text,
    'take_profit' : IDL.Float64,
    'alert_received_at' : Time,
    'duration_seconds' : IDL.Opt(IDL.Nat64),
    'strategy' : IDL.Text,
    'ghost_status' : GhostStatus,
    'created_at' : Time,
    'entry' : IDL.Float64,
    'avg_entry' : IDL.Opt(IDL.Float64),
    'stop_loss' : IDL.Float64,
    'trace_id' : TraceId,
    'avg_exit' : IDL.Opt(IDL.Float64),
    'tradovate_status' : TradeStatus,
  });
  const RiskMethod = IDL.Variant({
    'percentBalance' : IDL.Null,
    'fixedQuantity' : IDL.Null,
  });
  const Settings = IDL.Record({
    'pipeline_test_mode' : IDL.Bool,
    'ghost_exit_warn_ratio' : IDL.Float64,
    'ghost_api_key' : IDL.Text,
    'tradovate_live_url' : IDL.Text,
    'ghost_markup_pct' : IDL.Float64,
    'ghost_exit_warn_time_sec' : IDL.Nat64,
    'risk_method' : RiskMethod,
    'max_trade_quantity' : IDL.Nat,
    'ghost_executed_from_devices' : IDL.Vec(IDL.Text),
    'ghost_webhook_url' : IDL.Text,
    'tradovate_api_key' : IDL.Text,
    'tradovate_demo_url' : IDL.Text,
    'ghost_trade_max_qty_scale' : IDL.Nat,
    'ghost_spread_threshold' : IDL.Float64,
  });
  const EventSource = IDL.Variant({
    'tradovate' : IDL.Null,
    'ghost' : IDL.Null,
    'tradingview' : IDL.Null,
  });
  const EventType = IDL.Variant({
    'tradingviewEvent' : IDL.Null,
    'ghostForwardAttempt' : IDL.Null,
    'validationError' : IDL.Null,
    'ghostForwardSuccess' : IDL.Null,
    'ghostForwardFailure' : IDL.Null,
    'alertReceived' : IDL.Null,
    'ghostCallback' : IDL.Null,
  });
  const TraceEvent = IDL.Record({
    'id' : IDL.Nat,
    'source' : EventSource,
    'trace_id' : TraceId,
    'event_time' : Time,
    'event_type' : EventType,
  });
  const Fill = IDL.Record({
    'fill_time' : Time,
    'trace_id' : TraceId,
    'price' : IDL.Float64,
  });
  const WebhookStatus = IDL.Variant({
    'error' : IDL.Text,
    'processed' : IDL.Null,
    'received' : IDL.Null,
  });
  const WebhookAlert = IDL.Record({
    'status' : WebhookStatus,
    'received_at' : Time,
    'action' : IDL.Opt(IDL.Text),
    'ticker' : IDL.Opt(IDL.Text),
    'strategy' : IDL.Opt(IDL.Text),
    'alert_name' : IDL.Opt(IDL.Text),
    'raw_payload' : IDL.Text,
    'alert_id' : IDL.Text,
  });
  const TraceInput = IDL.Record({
    'action' : IDL.Text,
    'ticker' : IDL.Text,
    'take_profit' : IDL.Float64,
    'strategy' : IDL.Text,
    'params_snapshot_json' : IDL.Text,
    'entry' : IDL.Float64,
    'stop_loss' : IDL.Float64,
  });
  const ReceiveWebhookResponse = IDL.Record({
    'ok' : IDL.Bool,
    'error' : IDL.Opt(IDL.Text),
    'trace_id' : IDL.Opt(TraceId),
  });
  
  return IDL.Service({
    'filterTraces' : IDL.Func([TraceQueryFilters], [IDL.Vec(Trace)], ['query']),
    'getSettings' : IDL.Func([], [Settings], ['query']),
    'getTrace' : IDL.Func([TraceId], [IDL.Opt(Trace)], ['query']),
    'getTraceEvents' : IDL.Func([TraceId], [IDL.Vec(TraceEvent)], ['query']),
    'getTraceFills' : IDL.Func([TraceId], [IDL.Vec(Fill)], ['query']),
    'getWebhookAlert' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(WebhookAlert)],
        ['query'],
      ),
    'getWebhookAlerts' : IDL.Func([], [IDL.Vec(WebhookAlert)], ['query']),
    'listTraces' : IDL.Func([], [IDL.Vec(Trace)], ['query']),
    'receiveGhostCallback' : IDL.Func([IDL.Text], [], []),
    'receiveWebhook' : IDL.Func(
        [IDL.Opt(TraceInput), TraceId],
        [ReceiveWebhookResponse],
        [],
      ),
    'refreshTrace' : IDL.Func([TraceId], [], []),
    'saveSettings' : IDL.Func([Settings], [], []),
    'updateGhostStatus' : IDL.Func(
        [TraceId, GhostStatus, IDL.Text, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };