/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type EventSource = { 'tradovate' : null } |
  { 'ghost' : null } |
  { 'tradingview' : null };
export type EventType = { 'tradingviewEvent' : null } |
  { 'ghostForwardAttempt' : null } |
  { 'validationError' : null } |
  { 'ghostForwardSuccess' : null } |
  { 'ghostForwardFailure' : null } |
  { 'alertReceived' : null } |
  { 'ghostCallback' : null };
export interface Fill {
  'fill_time' : Time,
  'trace_id' : TraceId,
  'price' : number,
}
export type GhostStatus = { 'rejected' : null } |
  { 'accepted' : null } |
  { 'unknown' : null } |
  { 'received' : null };
export interface ReceiveWebhookResponse {
  'ok' : boolean,
  'error' : [] | [string],
  'trace_id' : [] | [TraceId],
}
export type RiskMethod = { 'percentBalance' : null } |
  { 'fixedQuantity' : null };
export interface Settings {
  'pipeline_test_mode' : boolean,
  'ghost_exit_warn_ratio' : number,
  'ghost_api_key' : string,
  'tradovate_live_url' : string,
  'ghost_markup_pct' : number,
  'ghost_exit_warn_time_sec' : bigint,
  'risk_method' : RiskMethod,
  'max_trade_quantity' : bigint,
  'ghost_executed_from_devices' : Array<string>,
  'ghost_webhook_url' : string,
  'tradovate_api_key' : string,
  'tradovate_demo_url' : string,
  'ghost_trade_max_qty_scale' : bigint,
  'ghost_spread_threshold' : number,
}
export type Time = bigint;
export interface Trace {
  'pnl' : [] | [number],
  'updated_at' : Time,
  'action' : string,
  'ticker' : string,
  'take_profit' : number,
  'alert_received_at' : Time,
  'duration_seconds' : [] | [bigint],
  'strategy' : string,
  'ghost_status' : GhostStatus,
  'created_at' : Time,
  'entry' : number,
  'avg_entry' : [] | [number],
  'stop_loss' : number,
  'trace_id' : TraceId,
  'avg_exit' : [] | [number],
  'tradovate_status' : TradeStatus,
}
export interface TraceEvent {
  'id' : bigint,
  'source' : EventSource,
  'trace_id' : TraceId,
  'event_time' : Time,
  'event_type' : EventType,
}
export type TraceId = string;
export interface TraceInput {
  'action' : string,
  'ticker' : string,
  'take_profit' : number,
  'strategy' : string,
  'params_snapshot_json' : string,
  'entry' : number,
  'stop_loss' : number,
}
export interface TraceQueryFilters {
  'ticker' : [] | [string],
  'strategy' : [] | [string],
  'ghost_status' : [] | [GhostStatus],
  'end_time' : [] | [Time],
  'start_time' : [] | [Time],
  'tradovate_status' : [] | [TradeStatus],
}
export type TradeStatus = { 'canceled' : null } |
  { 'submitted' : null } |
  { 'filled' : null } |
  { 'working' : null } |
  { 'rejected' : null } |
  { 'unknown' : null };
export interface WebhookAlert {
  'status' : WebhookStatus,
  'received_at' : Time,
  'action' : [] | [string],
  'ticker' : [] | [string],
  'strategy' : [] | [string],
  'alert_name' : [] | [string],
  'raw_payload' : string,
  'alert_id' : string,
}
export type WebhookStatus = { 'error' : string } |
  { 'processed' : null } |
  { 'received' : null };
export interface _SERVICE {
  'filterTraces' : ActorMethod<[TraceQueryFilters], Array<Trace>>,
  'getSettings' : ActorMethod<[], Settings>,
  'getTrace' : ActorMethod<[TraceId], [] | [Trace]>,
  'getTraceEvents' : ActorMethod<[TraceId], Array<TraceEvent>>,
  'getTraceFills' : ActorMethod<[TraceId], Array<Fill>>,
  'getWebhookAlert' : ActorMethod<[string], [] | [WebhookAlert]>,
  'getWebhookAlerts' : ActorMethod<[], Array<WebhookAlert>>,
  'listTraces' : ActorMethod<[], Array<Trace>>,
  'receiveGhostCallback' : ActorMethod<[string], undefined>,
  'receiveWebhook' : ActorMethod<
    [[] | [TraceInput], TraceId],
    ReceiveWebhookResponse
  >,
  'refreshTrace' : ActorMethod<[TraceId], undefined>,
  'saveSettings' : ActorMethod<[Settings], undefined>,
  'updateGhostStatus' : ActorMethod<
    [TraceId, GhostStatus, string, [] | [string]],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];